import XCTest

extension AccountUITests {
    @MainActor
    func testChoresEditArchiveRestoreAndKeepSharedHistory() async throws {
        executionTimeAllowance = 600
        continueAfterFailure = false
        let (app, home) = try await launchChores()
        _ = try await fixture("_fixture/deletion/receipt", body: ["householdId": home.id])
        try tap(app.buttons["Refresh chores"], in: app)
        let initial = try await choreState(home.id)
        let chore = try XCTUnwrap(initial.items.first { $0.title == "Wipe the fridge shelves" })
        try tap(app.otherElements["chore-\(chore.id)"].buttons["Mark done"], in: app)
        try tap(app.buttons["Record completion"], in: app)
        XCTAssertTrue(app.staticTexts["Chore completed."].waitForExistence(timeout: Wait.control))
        let before = try await choreState(home.id)
        let completed = try XCTUnwrap(before.items.first { $0.id == chore.id })
        XCTAssertFalse(before.history.isEmpty)
        try tap(app.buttons["Edit \(chore.title)"], in: app)
        XCTAssertEqual(app.textFields["Chore name"].value as? String, chore.title)
        XCTAssertEqual(picker("Repeat", in: app).value as? String, "Weekly")
        try fill(app.textFields["Chore name"], "Wipe the fridge doors")
        try choose("Every 2 weeks", from: "Repeat", in: app)
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["Chore saved."].waitForExistence(timeout: Wait.control))
        let editedState = try await choreState(home.id)
        let edited = try XCTUnwrap(editedState.items.first { $0.id == chore.id })
        XCTAssertEqual(edited.title, "Wipe the fridge doors")
        XCTAssertEqual(edited.notes, completed.notes)
        XCTAssertEqual(edited.repeatDays, 14)
        XCTAssertEqual(edited.dueDate, completed.dueDate)
        XCTAssertEqual(edited.rotation, completed.rotation)
        XCTAssertEqual(edited.turn, completed.turn)
        XCTAssertEqual(edited.occurrence, completed.occurrence)
        XCTAssertEqual(edited.version, completed.version + 1)
        XCTAssertEqual(editedState.historyDigest, before.historyDigest)
        XCTAssertEqual(editedState.ledgerDigest, before.ledgerDigest)
        try tap(app.buttons["Archive \(edited.title)"], in: app)
        XCTAssertTrue(app.staticTexts["Archive this chore?"].waitForExistence(timeout: Wait.control))
        try tap(app.buttons["Cancel"], in: app)
        let cancelled = try await choreState(home.id)
        XCTAssertEqual(cancelled.version, editedState.version)
        try tap(app.buttons["Archive \(edited.title)"], in: app)
        _ = try await fixture("_fixture/chores/failure", body: ["mode": "lost-response"])
        try tap(app.buttons["Archive chore"], in: app)
        XCTAssertTrue(app.staticTexts["chores-error"].waitForExistence(timeout: Wait.control))
        XCTAssertFalse(app.buttons["Done"].isEnabled)
        XCTAssertFalse(app.buttons["Cancel"].isEnabled)
        let uncertain = try await choreState(home.id)
        XCTAssertTrue(try XCTUnwrap(uncertain.items.first { $0.id == chore.id }).archived)
        try tap(app.buttons["Retry save"], in: app)
        XCTAssertTrue(app.staticTexts["Chore archived. Its history is kept."].waitForExistence(timeout: Wait.control))
        let archived = try await choreState(home.id)
        XCTAssertEqual(archived.version, uncertain.version)
        assertSameChoreRetry(archived)
        XCTAssertFalse(app.otherElements["chore-\(chore.id)"].exists)
        try selectSegment("Archived", from: "chore-sections", in: app)
        try tap(app.otherElements["chore-\(chore.id)"].buttons["Restore chore"], in: app)
        XCTAssertTrue(app.staticTexts["Restore this chore?"].waitForExistence(timeout: Wait.control))
        _ = try await fixture("_fixture/chores/failure", body: ["mode": "lost-response"])
        try tap(app.buttons["Restore chore"], in: app)
        XCTAssertTrue(app.staticTexts["chores-error"].waitForExistence(timeout: Wait.control))
        let restoredBeforeRetry = try await choreState(home.id)
        try tap(app.buttons["Retry save"], in: app)
        XCTAssertTrue(app.staticTexts["Chore restored with its saved schedule."].waitForExistence(timeout: Wait.control))
        let restoredState = try await choreState(home.id)
        let restored = try XCTUnwrap(restoredState.items.first { $0.id == chore.id })
        XCTAssertFalse(restored.archived)
        XCTAssertEqual(restored.version, edited.version + 2)
        XCTAssertEqual(restored.dueDate, edited.dueDate)
        XCTAssertEqual(restored.repeatDays, edited.repeatDays)
        XCTAssertEqual(restored.rotation, edited.rotation)
        XCTAssertEqual(restored.turn, edited.turn)
        XCTAssertEqual(restored.occurrence, edited.occurrence)
        XCTAssertEqual(restoredState.version, restoredBeforeRetry.version)
        XCTAssertEqual(restoredState.historyDigest, before.historyDigest)
        XCTAssertEqual(restoredState.ledgerDigest, before.ledgerDigest)
        assertSameChoreRetry(restoredState)
        try selectSegment("Chores", from: "chore-sections", in: app)
        let stored = try XCTUnwrap(initial.items.first { $0.title == "Clean the stored kettle" })
        XCTAssertFalse(app.buttons["Edit \(stored.title)"].isEnabled)
        try tap(app.buttons["Archive \(stored.title)"], in: app)
        try tap(app.buttons["Archive chore"], in: app)
        XCTAssertTrue(app.staticTexts["Chore archived. Its history is kept."].waitForExistence(timeout: Wait.control))
        try selectSegment("Archived", from: "chore-sections", in: app)
        XCTAssertFalse(app.otherElements["chore-\(stored.id)"].buttons["Restore chore"].isEnabled)
        app.terminate()
        app.launch()
        XCTAssertTrue(app.staticTexts["Cedar House"].waitForExistence(timeout: Wait.control))
        try openChores(app)
        XCTAssertTrue(app.staticTexts["Wipe the fridge doors"].waitForExistence(timeout: Wait.control))
        try selectSegment("History", from: "chore-sections", in: app)
        XCTAssertTrue(app.staticTexts["Wipe the fridge shelves"].waitForExistence(timeout: Wait.control))
    }

    @MainActor
    func testChoreEditsPreserveDraftsAndRequireConflictReview() async throws {
        executionTimeAllowance = 600
        continueAfterFailure = false
        let (app, home) = try await launchChores()
        let initial = try await choreState(home.id)
        let chore = try XCTUnwrap(initial.items.first { $0.title == "Wipe the fridge shelves" })
        try tap(app.buttons["Edit \(chore.title)"], in: app)
        try fill(app.textFields["Chore name"], "My first draft")
        _ = try await fixture("_fixture/chores/change", body: [
            "householdId": home.id, "choreId": chore.id, "title": "Changed on another device"
        ])
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["chores-error"].waitForExistence(timeout: Wait.control))
        XCTAssertFalse(app.buttons["Save chore"].isEnabled)
        XCTAssertFalse(app.staticTexts["Chore saved."].exists)
        XCTAssertEqual(app.textFields["Chore name"].value as? String, "My first draft")
        try tap(app.buttons["Review latest chores"], in: app)
        XCTAssertTrue(app.buttons["Use latest chore"].waitForExistence(timeout: Wait.control))
        XCTAssertEqual(app.textFields["Chore name"].value as? String, "My first draft")
        XCTAssertFalse(app.buttons["Save chore"].isEnabled)
        try tap(app.buttons["Use latest chore"], in: app)
        XCTAssertEqual(app.textFields["Chore name"].value as? String, "Changed on another device")
        try fill(app.textFields["Chore name"], "My reviewed draft")
        _ = try await fixture("_fixture/chores/change", body: [
            "householdId": home.id, "choreId": chore.id, "title": "A newer shared title"
        ])
        let latest = try await choreState(home.id)
        let latestChore = try XCTUnwrap(latest.items.first { $0.id == chore.id })
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["chores-error"].waitForExistence(timeout: Wait.control))
        try tap(app.buttons["Review latest chores"], in: app)
        XCTAssertTrue(app.buttons["Keep my draft"].waitForExistence(timeout: Wait.control))
        try tap(app.buttons["Keep my draft"], in: app)
        XCTAssertEqual(app.textFields["Chore name"].value as? String, "My reviewed draft")
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["Chore saved."].waitForExistence(timeout: Wait.control))
        let saved = try await choreState(home.id)
        XCTAssertEqual(saved.items.first { $0.id == chore.id }?.title, "My reviewed draft")
        XCTAssertEqual(saved.version, latest.version + 1)
        XCTAssertEqual(saved.items.first { $0.id == chore.id }?.version, latestChore.version + 1)
        XCTAssertEqual(saved.requests.last?.choreVersion, latestChore.version)
        XCTAssertEqual(saved.requests.last?.version, latest.version)
        XCTAssertEqual(saved.historyDigest, initial.historyDigest)
        XCTAssertEqual(saved.ledgerDigest, initial.ledgerDigest)
        XCTAssertTrue(saved.requests.allSatisfy { $0.method == "PATCH" && $0.native && !$0.browserHeaders })
    }

    @MainActor
    func testChoreEditsRetryAndScheduleCompletedOneOffsWithoutChangingHistory() async throws {
        executionTimeAllowance = 600
        continueAfterFailure = false
        let (app, home) = try await launchChores()
        let initial = try await choreState(home.id)
        let chore = try XCTUnwrap(initial.items.first { $0.title == "Wipe the fridge shelves" })
        try tap(app.buttons["Edit \(chore.title)"], in: app)
        try choose("One-off", from: "Repeat", in: app)
        _ = try await fixture("_fixture/chores/failure", body: ["mode": "lost-response"])
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["chores-error"].waitForExistence(timeout: Wait.control))
        XCTAssertFalse(app.staticTexts["Chore saved."].exists)
        XCTAssertFalse(app.buttons["Done"].isEnabled)
        XCTAssertFalse(app.buttons["Cancel"].isEnabled)
        XCTAssertFalse(picker("Repeat", in: app).isEnabled)
        let uncertain = try await choreState(home.id)
        XCTAssertNil(uncertain.items.first { $0.id == chore.id }?.repeatDays)
        try tap(app.buttons["Retry save"], in: app)
        XCTAssertTrue(app.staticTexts["Chore saved."].waitForExistence(timeout: Wait.control))
        let confirmed = try await choreState(home.id)
        XCTAssertEqual(confirmed.version, uncertain.version)
        assertSameChoreRetry(confirmed)
        try tap(app.otherElements["chore-\(chore.id)"].buttons["Mark done"], in: app)
        try tap(app.buttons["Record completion"], in: app)
        XCTAssertTrue(app.staticTexts["Chore completed."].waitForExistence(timeout: Wait.control))
        let completedState = try await choreState(home.id)
        let completed = try XCTUnwrap(completedState.items.first { $0.id == chore.id })
        let completion = try XCTUnwrap(completedState.history.first { $0.choreId == chore.id })
        XCTAssertNil(completed.dueDate)
        try selectSegment("History", from: "chore-sections", in: app)
        try tap(app.otherElements["completion-\(completion.id)"].buttons["Schedule again"], in: app)
        XCTAssertTrue(app.staticTexts["Schedule this chore again."].waitForExistence(timeout: Wait.control))
        XCTAssertEqual(app.textFields["Chore name"].value as? String, chore.title)
        XCTAssertEqual(picker("Repeat", in: app).value as? String, "One-off")
        try tap(app.buttons["Save chore"], in: app)
        XCTAssertTrue(app.staticTexts["Chore saved."].waitForExistence(timeout: Wait.control))
        let scheduledState = try await choreState(home.id)
        let scheduled = try XCTUnwrap(scheduledState.items.first { $0.id == chore.id })
        XCTAssertEqual(scheduled.dueDate, scheduledState.today)
        XCTAssertEqual(scheduled.occurrence, completed.occurrence)
        XCTAssertEqual(scheduled.version, completed.version + 1)
        XCTAssertEqual(scheduledState.historyDigest, completedState.historyDigest)
        XCTAssertEqual(scheduledState.ledgerDigest, initial.ledgerDigest)
        XCTAssertTrue(app.otherElements["chore-\(chore.id)"].buttons["Mark done"].isEnabled)
        try selectSegment("History", from: "chore-sections", in: app)
        XCTAssertFalse(app.otherElements["completion-\(completion.id)"].buttons["Schedule again"].exists)
        XCTAssertFalse(app.otherElements["completion-\(completion.id)"].buttons["Undo completion"].exists)
    }

    @MainActor
    private func assertSameChoreRetry(_ state: ChoreState) {
        let attempts = Array(state.requests.suffix(2))
        XCTAssertEqual(attempts.count, 2)
        XCTAssertNotNil(attempts.first?.mutationId)
        XCTAssertEqual(attempts.first?.mutationId, attempts.last?.mutationId)
        XCTAssertEqual(attempts.first?.choreVersion, attempts.last?.choreVersion)
        XCTAssertEqual(attempts.first?.version, attempts.last?.version)
        XCTAssertEqual(attempts.first?.mutationVersion, attempts.last?.mutationVersion)
        XCTAssertEqual(attempts.first?.path, attempts.last?.path)
        XCTAssertEqual(attempts.first?.method, "PATCH")
        XCTAssertEqual(attempts.last?.method, "PATCH")
    }
}
